### ISSUE TITLE
VDPAU_DRIVER broken for NVIDIA + Intel CPU

### ISSUE THREAD

**Issue by bbigras** [NixOS/nixos-hardware#388]
since https://github.com/NixOS/nixos-hardware/commit/1da3ba110c8940146588c9adf52811e70f449eb1, Chrome doesn't start anymore. See https://github.com/NixOS/nixpkgs/issues/162499

Should `common/gpu/nvidia.nix` just set `VDPAU_DRIVER` to `nvidia`?

@ilkecan

**Comment by ilkecan** [comment]
Assuming setting an environment variable like `VDPAU_DRIVER` is within the scope of this project, I think what you propose is the correct solution. Since `nvidia` is the default value, it should have priority over the `mkDefault` in the intel module, so something like `mkOverride 900 "nvidia"` could be used.

Also it might be a good idea to split the graphics related parts of `common/cpu/intel.nix` into a new file named `common/gpu/intel.nix`.

**Comment by 06kellyjac** [comment]
Just for my sake, where is `VDPAU_DRIVER`'s default set to nvidia?

---

As for your comment both changes sounds good

**Comment by ilkecan** [comment]
`VDPAU_DRIVER` is not set by default. In my experience the driver used defaults to `nvidia` when the environment variable is not set. I found this reasonable considering VDPAU was created by NVIDIA, so I didn't look into it further.
