### ISSUE TITLE
iptsd failing on suspension

### ISSUE THREAD

**Issue by Flameopathic** [NixOS/nixos-hardware#936]
`iptsd` fails when suspended, but can be manually restarted just fine. reported this to main repo [linux-surface/iptsd#162](https://github.com/linux-surface/iptsd/issues/162), but they noted that it functions well without the alterations made by this flake. why, then, does the flake not use the implementation of `iptsd` that is in `nixpkgs` and instead its own?

**Comment by Flameopathic** [comment]
oops, never pinged anyone. @iwanders @mexisme

**Comment by Flameopathic** [comment]
in addition, I find it odd how the folders under `microsoft` are structured. why is there one for `surface-pro/(3/9)` and one for `surface/pro-intel`? would there be any issues if I changed this to `surface/pro/(3/9/intel)` or `surface-pro/(3/9/intel)`? i know that some relative paths would have to be updated, but past that, it would be fine, right? also the configuration for the surface pro 3 seems kind of opinionated, is that okay here?

**Comment by iwanders** [comment]
I closed https://github.com/NixOS/nixos-hardware/pull/879 because the advice was to use the one from nixpkgs, so I feel we should consolidate on that version.

This is a good find though, does using the module from nixpkgs actually fix this? Because I've seen it happen on my device and I use the [microsoft-surface.ipts](https://github.com/iwanders/nixos-surface/blob/c5d9432fcf2ce9eadeef709d163e17c12be60935/module-desktop.nix#L17) module currently... I didn't really pursue this as I hardly use suspend, but let me know if using the one from nixpkgs works, in that case I'll switch to that for my install :)

I don't know too much about folder structures, I'm still learning when it comes to nix best practices.

**Comment by Flameopathic** [comment]
I have had no issues after using the one from nixpkgs. it's possible there are situations where it will break, but I havent encountered any. my recent pull request switches it to the version on nixpkgs and I've been running with it without issue.

**Comment by Flameopathic** [comment]
> I don't know too much about folder structures, I'm still learning when it comes to nix best practices.
it's just personal preference here, but consistency would be nice.

**Comment by iwanders** [comment]
> I have had no issues after using the one from nixpkgs. it's possible there are situations where it will break, but I havent encountered any.

Switched over and gave it a few suspend tests and the touch / pen kept working, so :+1:  Thanks!
